name: "Deploy para VPS"
on:
    push:
        branches:
            - master
jobs:
    build_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: "Baixar o código"
              uses: actions/checkout@v4

            - name: "Copiar arquivos para VPS"
              uses: appleboy/scp-action@v0.1.7
              with:
                host: "191.252.219.219"
                username: "root"
                password: ${{ secrets.SSH_PRIVATE_KEY }}
                source: "./index.html"
                target: "/teste"
            